language: generic

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker-cache/

env:
  - IMAGE=agileiot/agile-zb-armv7l

before_install:
  - for f in /home/travis/docker-cache/cache*.tar.gz; do
      gunzip -c $f | docker load || true;
    done

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build -t $IMAGE:$TRAVIS_BRANCH .
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
      mkdir -p $(dirname /home/travis/docker-cache/);
      docker save $(docker history -q $IMAGE:$TRAVIS_BRANCH | grep -v '<missing>') | gzip > /home/travis/docker-cache/cache-$TRAVIS_BRANCH.tar.gz;
    fi

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $IMAGE:$TRAVIS_BRANCH;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag $IMAGE:$TRAVIS_BRANCH $IMAGE;
      docker push $IMAGE;
    fi